version: 2
jobs:
  build-8.0.2:
    docker:
      - image: fpco/stack-build:lts-9.14

    working_directory: /home/stackage

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - restore_cache:
          keys:
          - v4-cache
          - v3-cache
      - run: stack upgrade --system-ghc
      - run: stack --version
      - run: stack build --test --only-snapshot --no-terminal --system-ghc -j 2 --stack-yaml=stack-8.0.2.yaml
      - run: stack install hoogle
      - run: hoogle generate
      - save_cache:
          key: v4-hoogle
          paths:
            - ~/.hoogle
      - save_cache:
          key: v4-cache
          paths:
            - ~/.stack
            - ~/.local
      - run: stack install --test --no-terminal --system-ghc -j 2 --no-run-tests --stack-yaml=stack-8.0.2.yaml
      - run:
          command: stack build --test --system-ghc -j 2 -v haskell-ide-engine --stack-yaml=stack-8.0.2.yaml
          no_output_timeout: 40m
      - run: cd ~ && tar cJvf hie.txz .local/bin/hie
      - store_artifacts:
          path: ~/hie.txz
          destination: hie-8.0.2.txz
      - store_test_results:
          path: ~/.stack-work/logs/*
  build-8.2.1:
    docker:
      - image: fpco/stack-build:lts-9.14

    working_directory: /home/stackage

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - restore_cache:
          key: v2-cache-8.2.1
      - run: stack upgrade --system-ghc
      - run: stack setup --no-terminal --stack-yaml=stack-8.2.1.yaml
      - run: stack build --test --only-snapshot --no-terminal --stack-yaml=stack-8.2.1.yaml -j 2
      - save_cache:
          key: v2-cache-8.2.1
          paths:
            - ~/.stack
            - ~/.local
      - run: stack install --test --no-terminal -j 2 --no-run-tests --stack-yaml=stack-8.2.1.yaml
      - run:
          command: stack install --test -j 2 haskell-ide-engine --stack-yaml=stack-8.2.1.yaml
          no_output_timeout: 40m
      - store_artifacts:
          path: ~/.local/bin/hie
          destination: hie-8.2.1
      - store_test_results:
          path: .stack-work/haskell-ide-engine-0.1.0.0-test.log
  build-8.2.2:
    docker:
      - image: fpco/stack-build:lts-9.14

    working_directory: /home/stackage

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - restore_cache:
          key: v2-cache-8.2.2
      - run: stack upgrade --system-ghc
      - run: stack setup --no-terminal --stack-yaml=stack.yaml
      - run: stack build --test --only-snapshot --no-terminal --stack-yaml=stack.yaml -j 2
      - save_cache:
          key: v2-cache-8.2.2
          paths:
            - ~/.stack
            - ~/.local
      - run: stack build --test --no-terminal -j 2 --no-run-tests --stack-yaml=stack.yaml
      - run:
          command: stack install --test -j 2 -v --cabal-verbose --stack-yaml=stack.yaml --no-terminal haskell-ide-engine

          no_output_timeout: 40m
      - store_artifacts:
          path: ~/.local/bin/hie
          destination: hie-8.2.2
      - store_test_results:
          path: .stack-work/logs/*
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-8.2.2
      - build-8.2.1
      - build-8.0.2
