version: 2
jobs:
  build-8.0.2:
    docker:
      - image: fpco/stack-build:lts-9.14

    working_directory: /home/stackage

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - restore_cache:
          key: v2-cache
      - run: stack build --test --only-dependencies --no-terminal --system-ghc -j 2
      - save_cache:
          key: v2-cache
          paths:
            - ~/.stack
            - ~/.local
      - run: stack install --test --no-terminal --system-ghc -j 2
      - store_artifacts:
          path: ~/.local/bin/hie
          destination: hie-8.0.2
      - store_test_results:
          path: ~/.stack-work/logs/*
  build-8.2.1:
    docker:
      - image: fpco/stack-build:lts-9.14

    working_directory: /home/stackage

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - restore_cache:
          key: v2-cache-8.2.1
      - run: stack upgrade --git --system-ghc
      - run: stack setup --no-terminal --stack-yaml=stack-8.2.1.yaml
      - run: stack build --test --only-dependencies --no-terminal --stack-yaml=stack-8.2.1.yaml -j 2
      - save_cache:
          key: v2-cache-8.2.1
          paths:
            - ~/.stack
            - ~/.local
      - run: stack install --test --no-terminal --system-ghc -j 2
      - store_artifacts:
          path: ~/.local/bin/hie
          destination: hie-8.2.1
      - store_test_results:
          path: ~/.stack-work/logs/*
  build-8.2.2:
    docker:
      - image: fpco/stack-build:lts-9.14

    working_directory: /home/stackage

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - restore_cache:
          key: v2-cache-8.2.2
      - run: stack upgrade --git --system-ghc
      - run: stack setup --no-terminal --stack-yaml=stack-8.2.2.yaml
      - run: stack build --test --only-dependencies --no-terminal --stack-yaml=stack-8.2.2.yaml -j 2
      - save_cache:
          key: v2-cache-8.2.2
          paths:
            - ~/.stack
            - ~/.local
      - run: stack install --test --no-terminal --system-ghc -j 2
      - store_artifacts:
          path: ~/.local/bin/hie
          destination: hie-8.2.2
      - store_test_results:
          path: ~/.stack-work/logs/*
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-8.2.2
      - build-8.2.1
      - build-8.0.2
